"""全站简体中文文案。"""

APP_TITLE = "黄金镯子检测系统"

# 主界面
BTN_MEASURE_DIAMETER = "测量内径"
BTN_READ_WEIGHT = "读取重量"
BTN_SAVE_RECORD = "保存记录"
BTN_SETTINGS = "打开设置"
BTN_EXPORT_CSV = "导出 CSV"
BTN_CONNECT = "连接设备"
BTN_DISCONNECT = "断开设备"
BTN_CALIBRATE = "标定向导"
BTN_SCALE_DEBUG = "串口调试"
BTN_ONE_CLICK_DETECT = "一键检测"
BTN_CLEAR_LOG = "清空日志"

LABEL_INNER_DIAMETER = "内径 (mm)"
LABEL_WEIGHT = "重量 (g)"
LABEL_STATUS = "状态"
LABEL_CAMERA_PREVIEW = "相机预览"
LABEL_HISTORY = "检测记录"

STATUS_READY = "就绪"
STATUS_MEASURING = "测量中..."
STATUS_STABLE = "稳定"
STATUS_UNSTABLE = "未稳定"
STATUS_CONNECTED = "已连接"
STATUS_DISCONNECTED = "未连接"
STATUS_MEASURE_FAILED = "测量失败"

COL_ID = "编号"
COL_TIME = "时间"
COL_DIAMETER = "内径(mm)"
COL_WEIGHT = "重量(g)"
COL_NOTES = "备注"

MSG_SAVE_OK = "记录已保存"
MSG_EXPORT_OK = "CSV 已导出"
MSG_CONNECT_OK = "设备连接成功"
MSG_DISCONNECT_OK = "设备已断开"
MSG_CALIBRATE_OK = "标定已保存：mm/px={value:.6f}，X={x:.6f}，Y={y:.6f}"
MSG_NO_CAMERA = "未配置相机"
MSG_NO_SCALE = "未配置电子秤"

# 设置
SETTINGS_TITLE = "工位设置"
TAB_CAMERA = "相机设置"
TAB_SCALE = "电子秤设置"
BTN_SAVE_SETTINGS = "保存设置"
BTN_CANCEL = "取消"

LABEL_CAMERA_KIND = "相机类型"
LABEL_CAMERA_IP = "相机 IP"
LABEL_EXPOSURE = "曝光 (μs)"
LABEL_GAIN = "增益"
LABEL_PROTOCOL = "协议"
LABEL_PORT = "串口"
LABEL_BAUDRATE = "波特率"
LABEL_BYTESIZE = "数据位"
LABEL_PARITY = "校验位"
LABEL_STOPBITS = "停止位"
LABEL_POLL_ENABLED = "启用轮询读数"
LABEL_POLL_INTERVAL = "轮询间隔 (ms)"
LABEL_POLL_COMMAND = "轮询命令 (hex)"
LABEL_STABLE_THRESHOLD = "稳定阈值 (g)"
LABEL_STABLE_COUNT = "连续稳定次数"
LABEL_PROTOCOL_IO = "协议文件"
BTN_IMPORT_PROTOCOL = "导入协议 YAML"
BTN_EXPORT_PROTOCOL = "导出协议 YAML"
MSG_PROTOCOL_IMPORTED = "已导入协议：{id}"
MSG_PROTOCOL_EXPORTED = "协议已导出"
MSG_ONE_CLICK_DONE = "一键检测完成"
MSG_ONE_CLICK_PARTIAL = "检测完成（部分项目失败）"
GIGE_DRIVER_TITLE = "GigE 网卡驱动"
GIGE_DRIVER_PROMPT = (
    "检测到工业相机 GigE 驱动安装包：\n{path}\n\n"
    "若相机无法发现或取流失败，请安装大华 GigE 驱动后重启。\n"
    "是否现在打开安装程序？"
)
MV_VIEWER_TITLE = "需安装大华 MV Viewer"
MV_VIEWER_PROMPT = (
    "未检测到大华工业相机 SDK（MV Viewer）。\n\n"
    "请在大华官网或随相机光盘获取 MV Viewer / 工业相机 SDK 安装包，"
    "在工控机上完整安装（含 GigE 网卡过滤驱动），安装后重启 GoldenV。\n\n"
    "安装路径通常为：\n"
    "  C:\\Program Files\\HuarayTech\\MV Viewer\n\n"
    "当前将使用模拟相机，无法进行真实取流。"
)
MSG_CAMERA_FALLBACK = (
    "未检测到大华 MVSDK。\n"
    "请先在工控机安装 MV Viewer，再重启本程序。\n"
    "当前已降级为模拟相机。"
)

# 标定
CALIBRATION_TITLE = "内径标定向导"
CALIBRATION_PROMPT = "放置已知内径的标准环规，输入标准值后测量并应用标定。"
LABEL_KNOWN_DIAMETER = "标准内径 (mm)"
BTN_RUN_CALIBRATION = "执行标定"
BTN_MEASURE_PREVIEW = "测量预览"
BTN_SAVE_MANUAL = "保存手动设置"
TAB_RING_CALIBRATION = "环规标定"
TAB_MANUAL_CALIBRATION = "手动调整"
LABEL_CURRENT_SCALE = "当前比例"
LABEL_RESULT_BEFORE = "标定前测量"
LABEL_RESULT_AFTER = "标定后测量"
LABEL_RESULT_ERROR = "相对误差"
LABEL_MM_PER_PIXEL = "mm/像素（统一）"
LABEL_MM_PER_PIXEL_X = "mm/像素 X"
LABEL_MM_PER_PIXEL_Y = "mm/像素 Y"
LABEL_SEPARATE_XY = "启用 X/Y 分向标定"
LABEL_CALIBRATION_HINT = "分向标定适用于像素比例在水平/垂直方向不一致的情况；内径换算取 X/Y 平均值。"
MSG_CALIBRATION_PREVIEW = "标定前：{before:.2f} mm"
MSG_CALIBRATION_APPLIED = (
    "标定前 {before:.2f} mm → 标定后 {after:.2f} mm\n"
    "误差 {error:.2f}%\n"
    "mm/px: {old_scale:.6f} → {new_scale:.6f}"
)
MSG_MANUAL_SAVED = "手动标定参数已保存"

# 调试
DEBUG_TITLE = "串口/协议调试"
LABEL_RAW_DATA = "原始数据"
LABEL_PARSE_RESULT = "解析结果"

ERROR_TITLE = "错误"
INFO_TITLE = "提示"
